server.port=8081
spring.application.name=polizas

spring.datasource.url=jdbc:h2:mem:polizasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true

springdoc.api-docs.path=/v3/api-docs
springdoc.packages-to-scan=com.seguros.polizas.interfaces.controller
springdoc.swagger-ui.path=/swagger-ui.html